name: Deploy Vite React App

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        # if your repo has a lockfile, prefer: npm ci

      - name: Build project
        run: npm run build

      - name: Prepare site folder
        run: |
          mkdir _site
          cp -r dist/* _site/
          cp _site/index.html _site/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
