name: Deploy Vite to GitHub Pages

on:
  push:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm ci || npm install

      # Build directly into _site so we deploy exactly what Vite outputs
      - name: Build (into _site)
        run: |
          npx vite build --base=/CICD_githubAction/ --outDir=_site
          cp _site/index.html _site/404.html

      # sanity check so we can see what's being deployed in the logs
      - name: Inspect artifact
        run: |
          echo "---- _site tree ----"; ls -lah _site
          echo "---- _site/assets ----"; ls -lah _site/assets || true
          echo "---- first 50 lines of _site/index.html ----"
          sed -n '1,50p' _site/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
